#! /usr/bin/env python
# encoding: utf-8

#bld.program(features='cxx',
#            source='complete_parser.cpp',
#            target='complete_parser',
#            use=['petro'])

bld.program(features='cxx',
            source='mp4_to_h264.cpp',
            target='mp4_to_h264',
            use=['petro'])

bld.program(features='cxx',
            source='mp4_to_aac.cpp',
            target='mp4_to_aac',
            use=['petro'])
